substitutions:
  _SERVICE: kayfabe-curator
  _REGION: us-central1
  _REPOSITORY: kayfabe-curator
  _IMAGE: ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$COMMIT_SHA

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - ${_IMAGE}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-secrets
      - YOUTUBE_API_KEY=YOUTUBE_API_KEY:latest
